name: Developers import in Apigee X

 

on:

#push:

   workflow_dispatch:
    inputs:
     deployment-org:

        type: choice

        description: Import to Org

        default: "centering-river-396816"

        options:

        - centering-river-396816

        - NA

        action-type:
          type: choice
          required : true
          description: Which action to perform ?
          default: "update"
          options:
          
           - importall
           - create   
           - update
           - delete

     developer-name:

        type: string

        required : false

        description: Developer name on which action will be performed ?

  

jobs:

  Apigee-X-Import-Developer:
    runs-on: ubuntu-latest
     permissions:
    contents: 'read'
    id-token: 'write'
   
    steps:

      - id: 'Checkout'

        name: Code checkout

        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'

        with:

            workload_identity_provider: "${{secrets.WORKLOAD_IDENTITY_PROVIDER }}"

            service_account: "${{ secrets.SERVICE_ACCOUNT }}"

            token_format: 'access_token'

            access_token_lifetime: '300s'

     

      - id: 'Script'

        name: Execute Power Shell Script

        shell: pwsh

        run: |

          ./scripts/developers.ps1 -accessToken "${{ steps.auth.outputs.access_token }}
