name: Developers import in Apigee X

 
on:
    
    workflow_dispatch:
     inputs:
      deployment-env:
        type: choice
        required: true
        description: Environment to deploy
        options:
          - eval
          - dev
          - test
          - uat
          - stage
          - prod
      deployment-region:
        type: choice
        description: Region to deploy
        options:
          - esi-apigee-x-394004
          - NA
      deployment-config:
        type: choice
        description: Config inputs
        options:
          - keyvaluemaps
          - flowhooks
          - apiproducts
          - developerapps
          - developers
          - importKeys

jobs:
  apigee-config-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'

        with:

            workload_identity_provider: "${{secrets.WORKLOAD_IDENTITY_PROVIDER }}"

            service_account: "${{ secrets.SERVICE_ACCOUNT }}"

            token_format: 'access_token'

            access_token_lifetime: '300s'

     

      - id: 'Script'

        name: Execute Power Shell Script

        shell: pwsh

        run: |

          ./scripts/developers.ps1 -accessToken "${{ steps.auth.outputs.access_token }}
